apiVersion: v1
kind: Pod
metadata:
  name: pi-pod
  labels:
    app: pi
spec:
  containers:
    - name: pi
      image: perl:5.32
      command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
  restartPolicy: Never
