apiVersion: v1
kind: Pod
metadata:
  name: pi-pod
  labels:
    app: pi
spec:
  containers:
    - name: pi
      image: perl:5.31
      command: ["perl",  "-Mbignum=bpi", "-wle", "print time()"]
  restartPolicy: Never
